import React, { useEffect, useMemo, useState } from 'react';
import {
  X, Check, ChevronLeft, ChevronRight, Sparkles,
  Package, Layers, MapPin, DollarSign, Image as ImageIcon,
  Sliders, Globe, Eye, FileText, Link2
} from 'lucide-react';

import {
  Product,
  ProductVariant,
  ProductEcommerce,
  ProductRelationships,
  SalesChannelsVisibility,
  CompositeComponentItem,
  BundleKitItem,
  BulkPackagingConfig,
  PackagingUnitsConfig,
  Category,
  ExtractedProductInfo,
  SerialNumberUnit,
} from '../types';
import { isSkuUnique } from '../utils/skuGenerator';
import { INITIAL_PRODUCTS } from '../data/mockData';

import StepBasicInfo from './product-form/StepBasicInfo';
import StepVariants from './product-form/StepVariants';
import StepInventory from './product-form/StepInventory';
import StepPricing from './product-form/StepPricing';
import StepMedia from './product-form/StepMedia';
import StepSpecifications from './product-form/StepSpecifications';
import StepEcommerce from './product-form/StepEcommerce';
import StepRelationships from './product-form/StepRelationships';
import StepReview from './product-form/StepReview';
import OpticalLaserScannerModal from './OpticalLaserScannerModal';
import AIProductPhotoScannerModal from './AIProductPhotoScannerModal';
import { normalizePriceListMap, priceListMapToItems } from '../utils/pricingEngine';

interface ProductFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (product: Product) => void | Promise<void>;
  initialProduct?: Product | null;
  existingCategories: string[];
  categoriesList?: Category[];
  existingBrands?: string[];
  allProducts?: Product[];
}

/**
 * IMPORTANT ARCHITECTURE NOTE
 *
 * This form is a catalog/product-definition editor.
 * It must NOT be used as the authoritative inventory ledger.
 *
 * In production:
 * - SKU/barcode uniqueness must be enforced by the backend/database.
 * - Stock changes should go through inventory transactions.
 * - Product IDs should be generated by the backend.
 * - Prices/money should be validated server-side using decimal/numeric types.
 * - AI extraction is untrusted input and must be reviewed/validated.
 */

const STEPS = [
  { id: 1, title: 'Basic Information', subtitle: 'Name, category, brand, status', icon: Package },
  { id: 2, title: 'Inventory Identity', subtitle: 'SKU, barcode, serial & batch rules', icon: MapPin },
  { id: 3, title: 'Variants & Options', subtitle: 'Size, color, SKU matrix', icon: Layers },
  { id: 4, title: 'Pricing Structure', subtitle: 'Cost, retail, wholesale & margin', icon: DollarSign },
  { id: 5, title: 'Media & Shots', subtitle: 'Gallery and primary image', icon: ImageIcon },
  { id: 6, title: 'Specifications', subtitle: 'Attributes & technical details', icon: Sliders },
  { id: 7, title: 'E-commerce', subtitle: 'SEO, URL slug & visibility', icon: Globe },
  { id: 8, title: 'Relationships', subtitle: 'Cross-sells, upsells & replacement', icon: Link2 },
  { id: 9, title: 'Review & Publish', subtitle: 'Review all changes before saving', icon: Eye },
] as const;

type TrackingMode = 'QUANTITY' | 'SERIAL' | 'BATCH' | 'NONE';
type RotationMethod = 'FIFO' | 'FEFO' | 'LIFO' | 'MANUAL';
type ProductStatus = 'Active' | 'Draft' | 'Archived';
type Location = 'Warehouse' | 'Store Shelf' | 'Fulfillment Center';

const DEFAULT_BULK_PACKAGING: BulkPackagingConfig = {
  outerPackageType: 'Box',
  itemsPerPackage: 30,
  outerPackageCost: 75,
  unitCost: 2.5,
  unitRetailPrice: 4,
  dozenRetailPrice: 42,
  outerPackageRetailPrice: 100,
  allowDozenSale: true,
  allowPackageSale: true,
};

const DEFAULT_PACKAGING_UNITS: PackagingUnitsConfig = {
  base_unit: 'piece',
  multiplier: 100,
  outerPackageType: 'Box',
  outerPackageCost: 25,
  units: [],
};

function makeSlug(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 120);
}

function cleanString(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

function toFiniteNumber(value: unknown, fallback = 0): number {
  const n = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function clampNonNegative(value: unknown): number {
  return Math.max(0, toFiniteNumber(value));
}

function createInitialForm(
  initialProduct: Product | null | undefined,
  existingCategories: string[]
) {
  if (initialProduct) {
    const tracking: TrackingMode =
      initialProduct.inventoryTracking ??
      (initialProduct.trackSerial
        ? 'SERIAL'
        : initialProduct.trackBatch
          ? 'BATCH'
          : initialProduct.trackStock === false
            ? 'NONE'
            : 'QUANTITY');

    const hasMultiUOM =
      initialProduct.hasMultiUOM ??
      Boolean(initialProduct.packagingUnits || initialProduct.bulkPackaging);

    const published = initialProduct.ecommerce?.published ?? true;

    return {
      name: cleanString(initialProduct.name),
      description: cleanString(initialProduct.description),
      brand: cleanString(initialProduct.brand),
      category: cleanString(initialProduct.category) || existingCategories[0] || 'General',
      productType: cleanString(initialProduct.productType) || 'Standard',
      status: initialProduct.status ?? 'Active',
      hasVariants: initialProduct.hasVariants ?? Boolean(initialProduct.variants?.length),
      inventoryTracking: tracking,
      trackStock: initialProduct.trackStock ?? (tracking !== 'NONE'),
      trackSerial: initialProduct.trackSerial ?? (tracking === 'SERIAL'),
      trackBatch: initialProduct.trackBatch ?? (tracking === 'BATCH'),
      trackExpiry: initialProduct.trackExpiry ?? Boolean(initialProduct.expiryDate),
      serialUnits: initialProduct.serialUnits ? [...initialProduct.serialUnits] : [],
      stockRotationMethod: initialProduct.stockRotationMethod ??
        (initialProduct.trackExpiry ? 'FEFO' : 'FIFO'),
      hasMultiUOM,
      returnable: initialProduct.returnable ?? true,

      variants: initialProduct.variants ? [...initialProduct.variants] : [],
      compositeComponents: initialProduct.compositeComponents
        ? [...initialProduct.compositeComponents]
        : [],
      bundleKitItems: initialProduct.bundleKitItems ? [...initialProduct.bundleKitItems] : [],
      bulkPackaging: initialProduct.bulkPackaging
        ? { ...initialProduct.bulkPackaging }
        : { ...DEFAULT_BULK_PACKAGING },
      packagingUnits: initialProduct.packagingUnits
        ? { ...initialProduct.packagingUnits }
        : {
            ...DEFAULT_PACKAGING_UNITS,
            base_unit: initialProduct.unit || 'piece',
            multiplier: initialProduct.bulkPackaging?.itemsPerPackage || 100,
          },

      sku: cleanString(initialProduct.sku),
      barcode: cleanString(initialProduct.barcode),
      qrCode: cleanString(initialProduct.qrCode),
      stock: clampNonNegative(initialProduct.stock),
      reorderPoint: clampNonNegative(initialProduct.reorderPoint),
      location: initialProduct.location ?? 'Store Shelf',
      unit: cleanString(initialProduct.unit) || 'pcs',
      serialNumber: cleanString(initialProduct.serialNumber),
      batchNumber: cleanString(initialProduct.batchNumber),
      expiryDate: cleanString(initialProduct.expiryDate),

      cost: clampNonNegative(initialProduct.cost),
      costCalculationMethod: initialProduct.costCalculationMethod || 'WEIGHTED_AVERAGE',
      price: clampNonNegative(initialProduct.price),
      wholesalePrice: clampNonNegative(initialProduct.wholesalePrice),
      minimumPrice: clampNonNegative(initialProduct.minimumPrice),
      originalPrice: clampNonNegative(initialProduct.originalPrice),
      priceLists: initialProduct.priceLists
        ? priceListMapToItems(normalizePriceListMap(initialProduct.priceLists, initialProduct.price))
        : [],

      imageUrl: cleanString(initialProduct.imageUrl),
      images: initialProduct.images ? [...initialProduct.images] : [],
      specifications: initialProduct.specifications
        ? { ...initialProduct.specifications }
        : {},

      salesChannels: {
        pos: initialProduct.salesChannels?.pos ?? true,
        ecommerce: initialProduct.salesChannels?.ecommerce ?? published,
        mobileApp: initialProduct.salesChannels?.mobileApp ?? false,
        wholesalePortal: initialProduct.salesChannels?.wholesalePortal ?? false,
      },
      publishToStore: published,
      ecommerce: initialProduct.ecommerce
        ? {
            published: initialProduct.ecommerce.published ?? published,
            storefrontStatus: initialProduct.ecommerce.storefrontStatus ?? (published ? 'Published' : 'Draft'),
            publishTargets: initialProduct.ecommerce.publishTargets ?? {
              website: initialProduct.salesChannels?.ecommerce ?? published,
              mobileApp: initialProduct.salesChannels?.mobileApp ?? false,
            },
            scheduledPublishDate: initialProduct.ecommerce.scheduledPublishDate ?? '',
            ...initialProduct.ecommerce,
          }
        : {
            published,
            storefrontStatus: published ? 'Published' : 'Draft',
            publishTargets: {
              website: published,
              mobileApp: false,
            },
            scheduledPublishDate: '',
            category: cleanString(initialProduct.category) || 'General',
            seoTitle: initialProduct.name ? `${initialProduct.name} | Official Store` : '',
            seoDescription: initialProduct.description || '',
            seoKeywords: initialProduct.category ? `${initialProduct.name}, ${initialProduct.category}, online store` : '',
            slug: makeSlug(initialProduct.name || ''),
            canonicalUrl: initialProduct.name ? `https://store.com/products/${makeSlug(initialProduct.name)}` : '',
            featured: Boolean(initialProduct.isFeatured),
            enableReviews: true,
            summary: cleanString(initialProduct.description),
          },
      relationships: initialProduct.relationships ? { ...initialProduct.relationships } : {},
    };
  }

  return {
    name: '',
    description: '',
    brand: '',
    category: existingCategories[0] || 'General',
    productType: 'Standard',
    status: 'Draft',
    hasVariants: false,
    inventoryTracking: 'QUANTITY',
    trackStock: true,
    trackSerial: false,
    trackBatch: false,
    trackExpiry: false,
    serialUnits: [] as SerialNumberUnit[],
    stockRotationMethod: 'FIFO',
    hasMultiUOM: false,
    returnable: true,

    variants: [] as ProductVariant[],
    compositeComponents: [] as CompositeComponentItem[],
    bundleKitItems: [] as BundleKitItem[],
    bulkPackaging: { ...DEFAULT_BULK_PACKAGING },
    packagingUnits: { ...DEFAULT_PACKAGING_UNITS },

    // Do not invent identifiers. Backend should assign them or the user should enter them.
    sku: '',
    barcode: '',
    qrCode: '',
    stock: 0,
    reorderPoint: 0,
    location: 'Store Shelf' as Location,
    unit: 'pcs',
    serialNumber: '',
    batchNumber: '',
    expiryDate: '',

    cost: 0,
    price: 0,
    wholesalePrice: 0,
    minimumPrice: 0,
    originalPrice: 0,

    imageUrl: '',
    images: [] as string[],
    specifications: {} as Record<string, string>,

    salesChannels: {
      pos: true,
      ecommerce: true,
      mobileApp: false,
      wholesalePortal: false,
    },
    publishToStore: false,
    ecommerce: {
      published: false,
      storefrontStatus: 'Draft',
      publishTargets: {
        website: true,
        mobileApp: false,
      },
      scheduledPublishDate: '',
      category: existingCategories[0] || 'General',
      seoTitle: '',
      seoDescription: '',
      seoKeywords: '',
      slug: '',
      canonicalUrl: '',
      featured: false,
      enableReviews: true,
      summary: '',
    } as ProductEcommerce,
    relationships: {} as ProductRelationships,
  };
}

export default function ProductFormModal({
  isOpen,
  onClose,
  onSave,
  initialProduct,
  existingCategories,
  categoriesList = [],
  existingBrands = [],
  allProducts = INITIAL_PRODUCTS,
}: ProductFormModalProps) {
  const allProductsList = useMemo(() => allProducts || INITIAL_PRODUCTS, [allProducts]);
  const [currentStep, setCurrentStep] = useState(1);
  const [form, setForm] = useState(() =>
    createInitialForm(initialProduct, existingCategories)
  );
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSaving, setIsSaving] = useState(false);
  const [isLaserModalOpen, setIsLaserModalOpen] = useState(false);
  const [laserScanTarget, setLaserScanTarget] =
    useState<'barcode' | 'sku' | 'qr' | 'serial' | 'batch'>('barcode');
  const [isAiPhotoModalOpen, setIsAiPhotoModalOpen] = useState(false);

  const update = <K extends keyof ReturnType<typeof createInitialForm>>(
    key: K,
    value: ReturnType<typeof createInitialForm>[K]
  ) => setForm(prev => ({ ...prev, [key]: value }));

  // Reset the complete draft whenever the modal opens or the edited product changes.
  useEffect(() => {
    if (!isOpen) return;
    setCurrentStep(1);
    setErrors({});
    setIsSaving(false);
    setForm(createInitialForm(initialProduct, existingCategories));
  }, [isOpen, initialProduct, existingCategories]);

  // Keep the mutually-exclusive inventory mode as the single source of truth.
  const trackingFlags = useMemo(() => ({
    trackStock: Boolean(form.trackStock),
    trackSerial: Boolean(form.trackSerial),
    trackBatch: Boolean(form.trackBatch),
    trackExpiry: Boolean(form.trackExpiry),
  }), [form.trackStock, form.trackSerial, form.trackBatch, form.trackExpiry]);

  const validateStep = (step: number) => {
    const next: Record<string, string> = {};

    if (step === 1) {
      if (!form.name.trim()) next.name = 'Product name is required.';
      if (!form.category.trim()) next.category = 'Category is required.';
    }

    if (step === 2) {
      if (!form.sku.trim()) {
        next.sku = 'SKU is required.';
      } else {
        const skuUniqueness = isSkuUnique(form.sku.trim(), allProductsList, {
          currentProductId: initialProduct?.id
        });
        if (!skuUniqueness.isUnique) {
          next.sku = `SKU "${form.sku.trim()}" is already taken by "${skuUniqueness.conflictingProduct?.name}". SKU must be globally unique.`;
        }
      }
      if (form.inventoryTracking === 'SERIAL' && !form.serialNumber.trim()) {
        next.serialNumber = 'Serial number is required for serial-tracked products.';
      }
      if (form.inventoryTracking === 'BATCH' && !form.batchNumber.trim()) {
        next.batchNumber = 'Batch number is required for batch-tracked products.';
      }
      if (trackingFlags.trackExpiry && form.inventoryTracking !== 'NONE' && !form.expiryDate) {
        // FEFO should not silently operate without an expiry date.
        next.expiryDate = 'Expiry date is required when expiry tracking/FEFO is enabled.';
      }
    }

    if (step === 3 && form.hasVariants) {
      if (!form.variants.length) next.variants = 'Add at least one variant or disable variants.';
      const duplicateSkus = new Set<string>();
      for (let i = 0; i < form.variants.length; i++) {
        const variant = form.variants[i];
        const variantSku = cleanString(variant.sku);
        if (variantSku) {
          if (duplicateSkus.has(variantSku.toLowerCase())) {
            next.variants = `Duplicate variant SKU within form: "${variant.sku}". Each variant SKU must be unique.`;
            break;
          }
          duplicateSkus.add(variantSku.toLowerCase());

          // Check global uniqueness against database
          const vUniqueness = isSkuUnique(variantSku, allProductsList, {
            currentProductId: initialProduct?.id,
            currentVariantSku: variantSku,
            excludeCurrentVariantIdx: i
          });
          if (!vUniqueness.isUnique) {
            next.variants = `Variant SKU "${variant.sku}" conflicts with product/variant "${vUniqueness.conflictingProduct?.name}". SKU must be globally unique.`;
            break;
          }
        }
      }
    }

    if (step === 4) {
      if (form.price <= 0) next.price = 'Retail price must be greater than zero.';
      if (form.cost < 0) next.cost = 'Cost cannot be negative.';
      if (form.cost > form.price) next.cost = 'Cost cannot be greater than retail price.';
      if (form.wholesalePrice < 0) next.wholesalePrice = 'Wholesale price cannot be negative.';
      if (form.minimumPrice < 0) next.minimumPrice = 'Minimum price cannot be negative.';
      if (form.minimumPrice > form.price) {
        next.minimumPrice = 'Minimum price cannot exceed retail price.';
      }
    }

    if (step === 5) {
      const invalidImage = form.images.some(url => {
        try {
          const parsed = new URL(url);
          return !['http:', 'https:'].includes(parsed.protocol);
        } catch {
          return true;
        }
      });
      if (invalidImage) next.images = 'One or more image URLs are invalid.';
    }

    if (step === 7) {
      const slug = form.ecommerce.slug || makeSlug(form.name);
      if (form.publishToStore && !slug) next.slug = 'A valid store URL slug is required.';
      if (form.ecommerce.seoTitle.length > 160) {
        next.seoTitle = 'SEO title should be 160 characters or fewer.';
      }
      if (form.ecommerce.seoDescription.length > 320) {
        next.seoDescription = 'SEO description should be 320 characters or fewer.';
      }
    }

    setErrors(next);
    return Object.keys(next).length === 0;
  };

  const validateAll = () => {
    for (const step of [1, 2, 3, 4, 5, 6, 7]) {
      if (!validateStep(step)) {
        setCurrentStep(step);
        return false;
      }
    }
    return true;
  };

  const handleNext = () => {
    if (validateStep(currentStep)) {
      setCurrentStep(step => Math.min(8, step + 1));
    }
  };

  const handleBack = () => {
    setCurrentStep(step => Math.max(1, step - 1));
    setErrors({});
  };

  const handleJumpToStep = (step: number) => {
    if (step <= currentStep) {
      setCurrentStep(step);
      setErrors({});
      return;
    }

    if (validateStep(currentStep)) {
      setCurrentStep(step);
    }
  };

  const handleApplyAiPhotoExtraction = (
    extracted: ExtractedProductInfo,
    imgUrl: string,
    allImages?: string[]
  ) => {
    const primary = cleanString(imgUrl) || cleanString(allImages?.[0]);
    const gallery = allImages?.filter(Boolean).map(cleanString) ?? (primary ? [primary] : []);

    setForm(prev => ({
      ...prev,
      name: cleanString(extracted.name) || prev.name,
      brand: cleanString(extracted.brand) || prev.brand,
      category: cleanString(extracted.category) || prev.category,
      description: cleanString(extracted.description) || prev.description,
      sku: cleanString(extracted.sku) || prev.sku,
      barcode: cleanString(extracted.barcode) || prev.barcode,
      // Never fabricate a QR identifier from an SKU.
      cost: extracted.suggestedCost != null ? clampNonNegative(extracted.suggestedCost) : prev.cost,
      price: extracted.suggestedPrice != null ? clampNonNegative(extracted.suggestedPrice) : prev.price,
      wholesalePrice:
        extracted.suggestedWholesalePrice != null
          ? clampNonNegative(extracted.suggestedWholesalePrice)
          : prev.wholesalePrice,
      stock:
        extracted.suggestedStock != null
          ? clampNonNegative(extracted.suggestedStock)
          : prev.stock,
      imageUrl: primary || prev.imageUrl,
      images: gallery.length ? gallery : prev.images,
      specifications: extracted.specifications
        ? { ...prev.specifications, ...extracted.specifications }
        : prev.specifications,
      ecommerce: extracted.name
        ? {
            ...prev.ecommerce,
            seoTitle: prev.ecommerce.seoTitle || `${cleanString(extracted.name)} | Official Store`,
            seoDescription:
              prev.ecommerce.seoDescription ||
              cleanString(extracted.shortSummary || extracted.description).slice(0, 320),
            slug: prev.ecommerce.slug || makeSlug(cleanString(extracted.name)),
            summary: prev.ecommerce.summary || cleanString(extracted.shortSummary),
          }
        : prev.ecommerce,
    }));
  };

  const openLaserScanner = (target: typeof laserScanTarget) => {
    setLaserScanTarget(target);
    setIsLaserModalOpen(true);
  };

  const handleScannedResult = (value: string) => {
    const scanned = cleanString(value);
    if (!scanned) return;

    if (laserScanTarget === 'barcode') update('barcode', scanned);
    else if (laserScanTarget === 'sku') update('sku', scanned);
    else if (laserScanTarget === 'qr') update('qrCode', scanned);
    else if (laserScanTarget === 'serial') update('serialNumber', scanned);
    else update('batchNumber', scanned);

    setErrors(prev => {
      const next = { ...prev };
      delete next[laserScanTarget === 'serial' ? 'serialNumber' :
        laserScanTarget === 'batch' ? 'batchNumber' : laserScanTarget];
      return next;
    });
    setIsLaserModalOpen(false);
  };

  const buildProduct = (finalStatus: ProductStatus): Product => {
    const images = form.images.filter(Boolean);
    const primaryImage = form.imageUrl || images[0] || '';

    return {
      ...(initialProduct ?? {}),
      // Preserve an existing ID; otherwise let the backend assign one where possible.
      id: initialProduct?.id ?? '',
      name: form.name.trim(),
      sku: form.sku.trim(),
      price: clampNonNegative(form.price),
      cost: clampNonNegative(form.cost),
      // This is the initial/catalog value only. Production inventory should reconcile it
      // through an opening-balance transaction rather than arbitrary edits.
      stock: trackingFlags.trackStock ? clampNonNegative(form.stock) : 0,
      category: form.category.trim() || 'General',
      location: form.location,
      reorderPoint: clampNonNegative(form.reorderPoint),
      barcode: form.barcode.trim(),
      qrCode: form.qrCode.trim(),
      variants: form.variants,
      salesCount: initialProduct?.salesCount ?? 0,
      imageUrl: primaryImage,
      images,
      description: form.description.trim(),
      brand: form.brand.trim(),
      rating: initialProduct?.rating ?? 0,
      reviewCount: initialProduct?.reviewCount ?? 0,
      originalPrice: form.originalPrice > form.price ? form.originalPrice : undefined,
      isFeatured: Boolean(form.ecommerce.featured),
      specifications: form.specifications,

      status: finalStatus,
      productType: form.productType,
      hasVariants: form.hasVariants,
      inventoryTracking: form.inventoryTracking,
      stockRotationMethod: form.stockRotationMethod,
      hasMultiUOM: form.hasMultiUOM,
      returnable: form.returnable,

      packagingUnits: form.hasMultiUOM ? form.packagingUnits : undefined,
      bulkPackaging: form.hasMultiUOM ? form.bulkPackaging : undefined,
      compositeComponents:
        form.productType === 'Composite' ? form.compositeComponents : undefined,
      bundleKitItems:
        form.productType === 'Bundle' ? form.bundleKitItems : undefined,

      wholesalePrice: form.wholesalePrice > 0 ? form.wholesalePrice : undefined,
      minimumPrice: form.minimumPrice > 0 ? form.minimumPrice : undefined,
      costCalculationMethod: form.costCalculationMethod || 'WEIGHTED_AVERAGE',
      priceLists: form.priceLists && form.priceLists.length > 0 ? form.priceLists : undefined,
      unit: form.unit.trim() || 'pcs',

      trackStock: trackingFlags.trackStock,
      trackSerial: trackingFlags.trackSerial,
      serialNumber: trackingFlags.trackSerial ? form.serialNumber.trim() : undefined,
      serialUnits: trackingFlags.trackSerial && form.serialUnits?.length > 0 ? form.serialUnits : undefined,
      trackBatch: trackingFlags.trackBatch,
      batchNumber: trackingFlags.trackBatch ? form.batchNumber.trim() : undefined,
      trackExpiry: trackingFlags.trackExpiry,
      expiryDate: trackingFlags.trackExpiry ? form.expiryDate : undefined,

      salesChannels: {
        ...form.salesChannels,
        ecommerce: form.ecommerce.storefrontStatus === 'Published' && (form.ecommerce.publishTargets?.website ?? true),
        mobileApp: form.ecommerce.storefrontStatus === 'Published' && (form.ecommerce.publishTargets?.mobileApp ?? false),
      },
      ecommerce: {
        ...form.ecommerce,
        published: finalStatus === 'Active' && form.ecommerce.storefrontStatus === 'Published' && (form.ecommerce.publishTargets?.website ?? true),
        storefrontStatus: form.ecommerce.storefrontStatus || 'Draft',
        publishTargets: form.ecommerce.publishTargets || { website: true, mobileApp: false },
        category: form.category.trim() || form.ecommerce.category,
        slug: form.ecommerce.slug.trim() || makeSlug(form.name),
      },
      relationships: form.relationships,
    };
  };

  const handleFinalSave = async (finalStatus: 'Active' | 'Draft') => {
    if (isSaving) return;
    if (!validateAll()) return;

    const product = buildProduct(finalStatus);

    setIsSaving(true);
    try {
      await onSave(product);
      onClose();
    } catch (error) {
      // Keep the modal open so the user does not lose their draft.
      setErrors({
        form:
          error instanceof Error
            ? error.message
            : 'Unable to save the product. Please try again.',
      });
    } finally {
      setIsSaving(false);
    }
  };

  if (!isOpen) return null;

  const step = STEPS[currentStep - 1];

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-0 backdrop-blur-sm sm:p-3 md:p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="product-form-title"
    >
      <div className="flex h-full w-full max-w-6xl flex-col overflow-hidden bg-white shadow-2xl sm:h-auto sm:max-h-[94vh] sm:rounded-3xl sm:border sm:border-slate-200">
        <header className="flex shrink-0 items-center justify-between border-b border-slate-800 bg-slate-950 px-4 py-3 text-white sm:px-5">
          <div className="flex min-w-0 items-center gap-3">
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-indigo-600">
              <Package className="h-5 w-5" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <h2 id="product-form-title" className="truncate text-sm font-bold sm:text-base">
                  {initialProduct ? 'Edit Product' : 'Create Product'}
                </h2>
                <span className="rounded-full bg-indigo-500/20 px-2 py-0.5 text-[10px] font-bold text-indigo-300">
                  {currentStep}/8
                </span>
              </div>
              <p className="truncate text-[11px] text-slate-400">
                {step.title} · {step.subtitle}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setIsAiPhotoModalOpen(true)}
              disabled={isSaving}
              className="flex items-center gap-1.5 rounded-xl bg-indigo-600 px-3 py-2 text-[11px] font-bold text-white hover:bg-indigo-500 disabled:opacity-50"
            >
              <Sparkles className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">AI Photo Scan</span>
              <span className="sm:hidden">AI Scan</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              disabled={isSaving}
              className="rounded-xl p-2 text-slate-400 hover:bg-slate-800 hover:text-white disabled:opacity-50"
              aria-label="Close product form"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </header>

        <nav className="shrink-0 overflow-x-auto border-b border-slate-200 bg-slate-50 px-3 py-2">
          <div className="flex min-w-max gap-1.5 sm:min-w-0">
            {STEPS.map(item => {
              const current = currentStep === item.id;
              const completed = currentStep > item.id;
              return (
                <button
                  key={item.id}
                  type="button"
                  onClick={() => handleJumpToStep(item.id)}
                  className={`flex items-center gap-2 rounded-xl border px-2 py-2 text-left transition ${
                    current
                      ? 'border-indigo-400 bg-white shadow-sm ring-2 ring-indigo-100'
                      : completed
                        ? 'border-emerald-200 bg-emerald-50'
                        : 'border-slate-200 bg-white/70 hover:bg-white'
                  }`}
                >
                  <span
                    className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-lg text-[10px] font-bold ${
                      current
                        ? 'bg-indigo-600 text-white'
                        : completed
                          ? 'bg-emerald-600 text-white'
                          : 'bg-slate-200 text-slate-600'
                    }`}
                  >
                    {completed ? <Check className="h-3.5 w-3.5" /> : item.id}
                  </span>
                  <span className="hidden max-w-[130px] truncate text-[10px] font-bold text-slate-700 md:block">
                    {item.title}
                  </span>
                </button>
              );
            })}
          </div>
        </nav>

        {errors.form && (
          <div className="mx-4 mt-3 shrink-0 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-medium text-rose-800 sm:mx-5">
            {errors.form}
          </div>
        )}

        <main className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5 md:p-6">
          {currentStep === 1 && (
            <StepBasicInfo
              name={form.name}
              setName={value => update('name', value)}
              description={form.description}
              setDescription={value => update('description', value)}
              brand={form.brand}
              setBrand={value => update('brand', value)}
              category={form.category}
              setCategory={value => update('category', value)}
              existingCategories={existingCategories}
              categoriesList={categoriesList}
              existingBrands={existingBrands}
              productType={form.productType}
              setProductType={value => update('productType', value)}
              hasVariants={form.hasVariants}
              setHasVariants={value => update('hasVariants', value)}
              inventoryTracking={form.inventoryTracking}
              setInventoryTracking={value => update('inventoryTracking', value)}
              trackExpiry={trackingFlags.trackExpiry}
              setTrackExpiry={value =>
                update('stockRotationMethod', value ? 'FEFO' : 'FIFO')
              }
              stockRotationMethod={form.stockRotationMethod}
              setStockRotationMethod={value => update('stockRotationMethod', value)}
              hasMultiUOM={form.hasMultiUOM}
              setHasMultiUOM={value => update('hasMultiUOM', value)}
              returnable={form.returnable}
              setReturnable={value => update('returnable', value)}
              status={form.status}
              setStatus={value => update('status', value)}
              errors={errors}
            />
          )}

          {currentStep === 2 && (
            <StepInventory
              sku={form.sku}
              setSku={value => update('sku', value)}
              barcode={form.barcode}
              setBarcode={value => update('barcode', value)}
              qrCode={form.qrCode}
              setQrCode={value => update('qrCode', value)}
              stock={form.stock}
              setStock={value => update('stock', clampNonNegative(value))}
              reorderPoint={form.reorderPoint}
              setReorderPoint={value => update('reorderPoint', clampNonNegative(value))}
              location={form.location}
              setLocation={value => update('location', value)}
              unit={form.unit}
              setUnit={value => update('unit', value)}
              trackStock={trackingFlags.trackStock}
              setTrackStock={value => update('trackStock', value)}
              trackSerial={trackingFlags.trackSerial}
              setTrackSerial={value => update('trackSerial', value)}
              serialNumber={form.serialNumber}
              setSerialNumber={value => update('serialNumber', value)}
              serialUnits={form.serialUnits}
              setSerialUnits={value => update('serialUnits', value)}
              trackBatch={trackingFlags.trackBatch}
              setTrackBatch={value => update('trackBatch', value)}
              batchNumber={form.batchNumber}
              setBatchNumber={value => update('batchNumber', value)}
              trackExpiry={trackingFlags.trackExpiry}
              setTrackExpiry={value => update('trackExpiry', value)}
              expiryDate={form.expiryDate}
              setExpiryDate={value => update('expiryDate', value)}
              onOpenLaserScanner={openLaserScanner}
              productType={form.productType}
              hasMultiUOM={form.hasMultiUOM}
              setHasMultiUOM={value => update('hasMultiUOM', value)}
              packagingUnits={form.packagingUnits}
              setPackagingUnits={value => update('packagingUnits', value)}
              compositeComponents={form.compositeComponents}
              bundleKitItems={form.bundleKitItems}
              bulkPackaging={form.bulkPackaging}
              setBulkPackaging={value => update('bulkPackaging', value)}
              cost={form.cost}
              setCost={value => update('cost', clampNonNegative(value))}
              price={form.price}
              setPrice={value => update('price', clampNonNegative(value))}
              errors={errors}
              brand={form.brand}
              productName={form.name}
              category={form.category}
              allProducts={allProductsList}
              currentProductId={initialProduct?.id}
            />
          )}

          {currentStep === 3 && (
            <StepVariants
              hasVariants={form.hasVariants}
              setHasVariants={value => update('hasVariants', value)}
              variants={form.variants}
              setVariants={value => update('variants', value)}
              parentSku={form.sku}
              basePrice={form.price}
              baseCost={form.cost}
              productType={form.productType}
              compositeComponents={form.compositeComponents}
              setCompositeComponents={value => update('compositeComponents', value)}
              bundleKitItems={form.bundleKitItems}
              setBundleKitItems={value => update('bundleKitItems', value)}
              setCost={value => update('cost', clampNonNegative(value))}
              setPrice={value => update('price', clampNonNegative(value))}
              setWholesalePrice={value => update('wholesalePrice', clampNonNegative(value))}
              setMinimumPrice={value => update('minimumPrice', clampNonNegative(value))}
              setOriginalPrice={value => update('originalPrice', clampNonNegative(value))}
              brand={form.brand}
              productName={form.name}
              category={form.category}
              allProducts={allProductsList}
              currentProductId={initialProduct?.id}
            />
          )}

          {currentStep === 4 && (
            <StepPricing
              cost={form.cost}
              setCost={value => update('cost', clampNonNegative(value))}
              price={form.price}
              setPrice={value => update('price', clampNonNegative(value))}
              wholesalePrice={form.wholesalePrice}
              setWholesalePrice={value => update('wholesalePrice', clampNonNegative(value))}
              minimumPrice={form.minimumPrice}
              setMinimumPrice={value => update('minimumPrice', clampNonNegative(value))}
              originalPrice={form.originalPrice}
              setOriginalPrice={value => update('originalPrice', clampNonNegative(value))}
              costCalculationMethod={form.costCalculationMethod}
              setCostCalculationMethod={value => update('costCalculationMethod', value)}
              priceLists={form.priceLists}
              setPriceLists={value => update('priceLists', value)}
              productType={form.productType}
              compositeComponents={form.compositeComponents}
              bundleKitItems={form.bundleKitItems}
              bulkPackaging={form.bulkPackaging}
              setBulkPackaging={value => update('bulkPackaging', value)}
              errors={errors}
            />
          )}

          {currentStep === 5 && (
            <StepMedia
              imageUrl={form.imageUrl}
              setImageUrl={value => update('imageUrl', value)}
              images={form.images}
              setImages={value => update('images', value)}
              variants={form.variants}
              setVariants={value => update('variants', value)}
            />
          )}

          {currentStep === 6 && (
            <StepSpecifications
              specifications={form.specifications}
              setSpecifications={value => update('specifications', value)}
            />
          )}

          {currentStep === 7 && (
            <StepEcommerce
              productName={form.name}
              category={form.category}
              ecommerce={form.ecommerce}
              setEcommerce={value =>
                update('ecommerce', {
                  ...value,
                  slug: cleanString(value.slug) || makeSlug(form.name),
                })
              }
              salesChannels={form.salesChannels}
              setSalesChannels={value => update('salesChannels', value)}
            />
          )}

          {currentStep === 8 && (
            <StepRelationships
              productName={form.name}
              category={form.category}
              brand={form.brand}
              currentProductId={initialProduct?.id}
              relationships={form.relationships}
              setRelationships={value => update('relationships', value)}
              allProducts={allProducts}
            />
          )}

          {currentStep === 9 && (
            <StepReview
              productData={{
                name: form.name,
                brand: form.brand,
                category: form.category,
                description: form.description,
                productType: form.productType,
                status: form.status,
                hasVariants: form.hasVariants,
                variants: form.variants,
                compositeComponents: form.compositeComponents,
                bundleKitItems: form.bundleKitItems,
                bulkPackaging: form.bulkPackaging,
                sku: form.sku,
                barcode: form.barcode,
                qrCode: form.qrCode,
                stock: form.stock,
                reorderPoint: form.reorderPoint,
                unit: form.unit,
                location: form.location,
                trackStock: trackingFlags.trackStock,
                trackSerial: trackingFlags.trackSerial,
                serialNumber: form.serialNumber,
                trackBatch: trackingFlags.trackBatch,
                batchNumber: form.batchNumber,
                trackExpiry: trackingFlags.trackExpiry,
                expiryDate: form.expiryDate,
                cost: form.cost,
                price: form.price,
                wholesalePrice: form.wholesalePrice,
                minimumPrice: form.minimumPrice,
                originalPrice: form.originalPrice,
                priceLists: form.priceLists,
                imageUrl: form.imageUrl,
                images: form.images,
                specifications: form.specifications,
                ecommerce: form.ecommerce,
              }}
              publishToStore={form.publishToStore}
              setPublishToStore={value => {
                update('publishToStore', value);
                update('ecommerce', { ...form.ecommerce, published: value });
              }}
              onJumpToStep={handleJumpToStep}
              onSave={status => handleFinalSave(status)}
            />
          )}
        </main>

        <footer className="flex shrink-0 items-center justify-between gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 sm:px-5">
          <button
            type="button"
            onClick={handleBack}
            disabled={currentStep === 1 || isSaving}
            className="flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 disabled:cursor-not-allowed disabled:opacity-40"
          >
            <ChevronLeft className="h-4 w-4" />
            <span className="hidden sm:inline">Previous</span>
          </button>

          <div className="flex items-center gap-2">
            {currentStep < 8 && (
              <button
                type="button"
                onClick={() => handleFinalSave('Draft')}
                disabled={isSaving}
                className="flex items-center gap-1.5 rounded-xl bg-slate-200 px-3 py-2 text-xs font-bold text-slate-800 hover:bg-slate-300 disabled:opacity-50"
              >
                <FileText className="h-3.5 w-3.5" />
                Save Draft
              </button>
            )}

            {currentStep < 8 ? (
              <button
                type="button"
                onClick={handleNext}
                disabled={isSaving}
                className="flex items-center gap-1.5 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50"
              >
                Next
                <ChevronRight className="h-4 w-4" />
              </button>
            ) : (
              <button
                type="button"
                onClick={() => handleFinalSave('Active')}
                disabled={isSaving}
                className="flex items-center gap-1.5 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-emerald-700 disabled:opacity-50"
              >
                <Sparkles className="h-4 w-4" />
                {isSaving ? 'Saving…' : 'Publish Product'}
              </button>
            )}
          </div>
        </footer>
      </div>

      <OpticalLaserScannerModal
        isOpen={isLaserModalOpen}
        onClose={() => setIsLaserModalOpen(false)}
        onScanSuccess={handleScannedResult}
      />

      <AIProductPhotoScannerModal
        isOpen={isAiPhotoModalOpen}
        onClose={() => setIsAiPhotoModalOpen(false)}
        onApplyToForm={handleApplyAiPhotoExtraction}
      />
    </div>
  );
}
